project: 
  type: website
  output-dir: docs

website:
  title: "LiangLai Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/starter-analysis-exercise.qmd
          - text: "READy Exercise"
            file: ready-exercise/ready-exercise.html
          - text: "Data Exercise"
            file: data-exercise/data-exercise.html
          - text: "Data Analysis Exercise"
            file: cdcdata-exercise/cdcdata-exercise.html
          - text: "presentation-exercise"
            file: presentation-exercise/presentation-exercise.html
    right:
      - icon: github 
        href: https://github.com/LiangLai/Lianglai-portfolio   
format:
  html:
    theme: cosmo
    highlight: zenburn
    css: styles.css
    toc: FALSE